apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-device-wo-nb001-p00001
  namespace: ktwin
spec:
  interface: ngsi-ld-city-device
  twinInstanceRelationships:
  - name: refDeviceModel
    instance: ngsi-ld-city-devicemodel-wo-nb001-p00001
    interface: ngsi-ld-city-devicemodel
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-device-wo-nb001-p00002
  namespace: ktwin
spec:
  interface: ngsi-ld-city-device
  twinInstanceRelationships:
  - name: refDeviceModel
    instance: ngsi-ld-city-devicemodel-wo-nb001-p00002
    interface: ngsi-ld-city-devicemodel
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-device-wo-nb001-p00003
  namespace: ktwin
spec:
  interface: ngsi-ld-city-device
  twinInstanceRelationships:
  - name: refDeviceModel
    instance: ngsi-ld-city-devicemodel-wo-nb001-p00003
    interface: ngsi-ld-city-devicemodel
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-device-wo-nb001-p00004
  namespace: ktwin
spec:
  interface: ngsi-ld-city-device
  twinInstanceRelationships:
  - name: refDeviceModel
    instance: ngsi-ld-city-devicemodel-wo-nb001-p00004
    interface: ngsi-ld-city-devicemodel
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-device-wo-nb001-p00005
  namespace: ktwin
spec:
  interface: ngsi-ld-city-device
  twinInstanceRelationships:
  - name: refDeviceModel
    instance: ngsi-ld-city-devicemodel-wo-nb001-p00005
    interface: ngsi-ld-city-devicemodel
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-device-wo-nb001-p00006
  namespace: ktwin
spec:
  interface: ngsi-ld-city-device
  twinInstanceRelationships:
  - name: refDeviceModel
    instance: ngsi-ld-city-devicemodel-wo-nb001-p00006
    interface: ngsi-ld-city-devicemodel
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-device-wo-nb001-p00007
  namespace: ktwin
spec:
  interface: ngsi-ld-city-device
  twinInstanceRelationships:
  - name: refDeviceModel
    instance: ngsi-ld-city-devicemodel-wo-nb001-p00007
    interface: ngsi-ld-city-devicemodel
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-device-wo-nb001-p00008
  namespace: ktwin
spec:
  interface: ngsi-ld-city-device
  twinInstanceRelationships:
  - name: refDeviceModel
    instance: ngsi-ld-city-devicemodel-wo-nb001-p00008
    interface: ngsi-ld-city-devicemodel
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-device-wo-nb001-p00009
  namespace: ktwin
spec:
  interface: ngsi-ld-city-device
  twinInstanceRelationships:
  - name: refDeviceModel
    instance: ngsi-ld-city-devicemodel-wo-nb001-p00009
    interface: ngsi-ld-city-devicemodel
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-device-wo-nb001-p00010
  namespace: ktwin
spec:
  interface: ngsi-ld-city-device
  twinInstanceRelationships:
  - name: refDeviceModel
    instance: ngsi-ld-city-devicemodel-wo-nb001-p00010
    interface: ngsi-ld-city-devicemodel
status: {}