apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: city-pole-nb001-p00001
  namespace: ktwin
spec:
  interface: city-pole
  twinInstanceRelationships:
  - instance: s4city-city-neighborhood-nb001
    interface: s4city-city-neighborhood
    name: refNeighborhood
  - instance: ngsi-ld-city-streetlight-nb001-p00001
    interface: ngsi-ld-city-streetlight
    name: refStreetlight
  - instance: ngsi-ld-city-airqualityobserved-nb001-p00001
    interface: ngsi-ld-city-airqualityobserved
    name: refAirQualityObserved
  - instance: ngsi-ld-city-noiselevelobserved-nb001-p00001
    interface: ngsi-ld-city-noiselevelobserved
    name: refNoiseLevel
  - instance: ngsi-ld-city-weatherobserved-nb001-p00001
    interface: ngsi-ld-city-weatherobserved
    name: refWeather
  - instance: ngsi-ld-city-crowdflowobserved-nb001-p00001
    interface: ngsi-ld-city-crowdflowobserved
    name: refCrowdFlow
  - instance: ngsi-ld-city-evchargingstation-nb001-p00001
    interface: ngsi-ld-city-evchargingstation
    name: refEVChargingStation
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: city-pole-nb001-p00002
  namespace: ktwin
spec:
  interface: city-pole
  twinInstanceRelationships:
  - instance: s4city-city-neighborhood-nb001
    interface: s4city-city-neighborhood
    name: refNeighborhood
  - instance: ngsi-ld-city-streetlight-nb001-p00002
    interface: ngsi-ld-city-streetlight
    name: refStreetlight
  - instance: ngsi-ld-city-airqualityobserved-nb001-p00002
    interface: ngsi-ld-city-airqualityobserved
    name: refAirQualityObserved
  - instance: ngsi-ld-city-noiselevelobserved-nb001-p00002
    interface: ngsi-ld-city-noiselevelobserved
    name: refNoiseLevel
  - instance: ngsi-ld-city-weatherobserved-nb001-p00002
    interface: ngsi-ld-city-weatherobserved
    name: refWeather
  - instance: ngsi-ld-city-crowdflowobserved-nb001-p00002
    interface: ngsi-ld-city-crowdflowobserved
    name: refCrowdFlow
  - instance: ngsi-ld-city-evchargingstation-nb001-p00002
    interface: ngsi-ld-city-evchargingstation
    name: refEVChargingStation
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: city-pole-nb001-p00003
  namespace: ktwin
spec:
  interface: city-pole
  twinInstanceRelationships:
  - instance: s4city-city-neighborhood-nb001
    interface: s4city-city-neighborhood
    name: refNeighborhood
  - instance: ngsi-ld-city-streetlight-nb001-p00003
    interface: ngsi-ld-city-streetlight
    name: refStreetlight
  - instance: ngsi-ld-city-airqualityobserved-nb001-p00003
    interface: ngsi-ld-city-airqualityobserved
    name: refAirQualityObserved
  - instance: ngsi-ld-city-noiselevelobserved-nb001-p00003
    interface: ngsi-ld-city-noiselevelobserved
    name: refNoiseLevel
  - instance: ngsi-ld-city-weatherobserved-nb001-p00003
    interface: ngsi-ld-city-weatherobserved
    name: refWeather
  - instance: ngsi-ld-city-crowdflowobserved-nb001-p00003
    interface: ngsi-ld-city-crowdflowobserved
    name: refCrowdFlow
  - instance: ngsi-ld-city-evchargingstation-nb001-p00003
    interface: ngsi-ld-city-evchargingstation
    name: refEVChargingStation
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: city-pole-nb001-p00004
  namespace: ktwin
spec:
  interface: city-pole
  twinInstanceRelationships:
  - instance: s4city-city-neighborhood-nb001
    interface: s4city-city-neighborhood
    name: refNeighborhood
  - instance: ngsi-ld-city-streetlight-nb001-p00004
    interface: ngsi-ld-city-streetlight
    name: refStreetlight
  - instance: ngsi-ld-city-airqualityobserved-nb001-p00004
    interface: ngsi-ld-city-airqualityobserved
    name: refAirQualityObserved
  - instance: ngsi-ld-city-noiselevelobserved-nb001-p00004
    interface: ngsi-ld-city-noiselevelobserved
    name: refNoiseLevel
  - instance: ngsi-ld-city-weatherobserved-nb001-p00004
    interface: ngsi-ld-city-weatherobserved
    name: refWeather
  - instance: ngsi-ld-city-crowdflowobserved-nb001-p00004
    interface: ngsi-ld-city-crowdflowobserved
    name: refCrowdFlow
  - instance: ngsi-ld-city-evchargingstation-nb001-p00004
    interface: ngsi-ld-city-evchargingstation
    name: refEVChargingStation
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: city-pole-nb001-p00005
  namespace: ktwin
spec:
  interface: city-pole
  twinInstanceRelationships:
  - instance: s4city-city-neighborhood-nb001
    interface: s4city-city-neighborhood
    name: refNeighborhood
  - instance: ngsi-ld-city-streetlight-nb001-p00005
    interface: ngsi-ld-city-streetlight
    name: refStreetlight
  - instance: ngsi-ld-city-airqualityobserved-nb001-p00005
    interface: ngsi-ld-city-airqualityobserved
    name: refAirQualityObserved
  - instance: ngsi-ld-city-noiselevelobserved-nb001-p00005
    interface: ngsi-ld-city-noiselevelobserved
    name: refNoiseLevel
  - instance: ngsi-ld-city-weatherobserved-nb001-p00005
    interface: ngsi-ld-city-weatherobserved
    name: refWeather
  - instance: ngsi-ld-city-crowdflowobserved-nb001-p00005
    interface: ngsi-ld-city-crowdflowobserved
    name: refCrowdFlow
  - instance: ngsi-ld-city-evchargingstation-nb001-p00005
    interface: ngsi-ld-city-evchargingstation
    name: refEVChargingStation
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: city-pole-nb001-p00006
  namespace: ktwin
spec:
  interface: city-pole
  twinInstanceRelationships:
  - instance: s4city-city-neighborhood-nb001
    interface: s4city-city-neighborhood
    name: refNeighborhood
  - instance: ngsi-ld-city-streetlight-nb001-p00006
    interface: ngsi-ld-city-streetlight
    name: refStreetlight
  - instance: ngsi-ld-city-airqualityobserved-nb001-p00006
    interface: ngsi-ld-city-airqualityobserved
    name: refAirQualityObserved
  - instance: ngsi-ld-city-noiselevelobserved-nb001-p00006
    interface: ngsi-ld-city-noiselevelobserved
    name: refNoiseLevel
  - instance: ngsi-ld-city-weatherobserved-nb001-p00006
    interface: ngsi-ld-city-weatherobserved
    name: refWeather
  - instance: ngsi-ld-city-crowdflowobserved-nb001-p00006
    interface: ngsi-ld-city-crowdflowobserved
    name: refCrowdFlow
  - instance: ngsi-ld-city-evchargingstation-nb001-p00006
    interface: ngsi-ld-city-evchargingstation
    name: refEVChargingStation
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: city-pole-nb001-p00007
  namespace: ktwin
spec:
  interface: city-pole
  twinInstanceRelationships:
  - instance: s4city-city-neighborhood-nb001
    interface: s4city-city-neighborhood
    name: refNeighborhood
  - instance: ngsi-ld-city-streetlight-nb001-p00007
    interface: ngsi-ld-city-streetlight
    name: refStreetlight
  - instance: ngsi-ld-city-airqualityobserved-nb001-p00007
    interface: ngsi-ld-city-airqualityobserved
    name: refAirQualityObserved
  - instance: ngsi-ld-city-noiselevelobserved-nb001-p00007
    interface: ngsi-ld-city-noiselevelobserved
    name: refNoiseLevel
  - instance: ngsi-ld-city-weatherobserved-nb001-p00007
    interface: ngsi-ld-city-weatherobserved
    name: refWeather
  - instance: ngsi-ld-city-crowdflowobserved-nb001-p00007
    interface: ngsi-ld-city-crowdflowobserved
    name: refCrowdFlow
  - instance: ngsi-ld-city-evchargingstation-nb001-p00007
    interface: ngsi-ld-city-evchargingstation
    name: refEVChargingStation
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: city-pole-nb001-p00008
  namespace: ktwin
spec:
  interface: city-pole
  twinInstanceRelationships:
  - instance: s4city-city-neighborhood-nb001
    interface: s4city-city-neighborhood
    name: refNeighborhood
  - instance: ngsi-ld-city-streetlight-nb001-p00008
    interface: ngsi-ld-city-streetlight
    name: refStreetlight
  - instance: ngsi-ld-city-airqualityobserved-nb001-p00008
    interface: ngsi-ld-city-airqualityobserved
    name: refAirQualityObserved
  - instance: ngsi-ld-city-noiselevelobserved-nb001-p00008
    interface: ngsi-ld-city-noiselevelobserved
    name: refNoiseLevel
  - instance: ngsi-ld-city-weatherobserved-nb001-p00008
    interface: ngsi-ld-city-weatherobserved
    name: refWeather
  - instance: ngsi-ld-city-crowdflowobserved-nb001-p00008
    interface: ngsi-ld-city-crowdflowobserved
    name: refCrowdFlow
  - instance: ngsi-ld-city-evchargingstation-nb001-p00008
    interface: ngsi-ld-city-evchargingstation
    name: refEVChargingStation
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: city-pole-nb001-p00009
  namespace: ktwin
spec:
  interface: city-pole
  twinInstanceRelationships:
  - instance: s4city-city-neighborhood-nb001
    interface: s4city-city-neighborhood
    name: refNeighborhood
  - instance: ngsi-ld-city-streetlight-nb001-p00009
    interface: ngsi-ld-city-streetlight
    name: refStreetlight
  - instance: ngsi-ld-city-airqualityobserved-nb001-p00009
    interface: ngsi-ld-city-airqualityobserved
    name: refAirQualityObserved
  - instance: ngsi-ld-city-noiselevelobserved-nb001-p00009
    interface: ngsi-ld-city-noiselevelobserved
    name: refNoiseLevel
  - instance: ngsi-ld-city-weatherobserved-nb001-p00009
    interface: ngsi-ld-city-weatherobserved
    name: refWeather
  - instance: ngsi-ld-city-crowdflowobserved-nb001-p00009
    interface: ngsi-ld-city-crowdflowobserved
    name: refCrowdFlow
  - instance: ngsi-ld-city-evchargingstation-nb001-p00009
    interface: ngsi-ld-city-evchargingstation
    name: refEVChargingStation
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: city-pole-nb001-p00010
  namespace: ktwin
spec:
  interface: city-pole
  twinInstanceRelationships:
  - instance: s4city-city-neighborhood-nb001
    interface: s4city-city-neighborhood
    name: refNeighborhood
  - instance: ngsi-ld-city-streetlight-nb001-p00010
    interface: ngsi-ld-city-streetlight
    name: refStreetlight
  - instance: ngsi-ld-city-airqualityobserved-nb001-p00010
    interface: ngsi-ld-city-airqualityobserved
    name: refAirQualityObserved
  - instance: ngsi-ld-city-noiselevelobserved-nb001-p00010
    interface: ngsi-ld-city-noiselevelobserved
    name: refNoiseLevel
  - instance: ngsi-ld-city-weatherobserved-nb001-p00010
    interface: ngsi-ld-city-weatherobserved
    name: refWeather
  - instance: ngsi-ld-city-crowdflowobserved-nb001-p00010
    interface: ngsi-ld-city-crowdflowobserved
    name: refCrowdFlow
  - instance: ngsi-ld-city-evchargingstation-nb001-p00010
    interface: ngsi-ld-city-evchargingstation
    name: refEVChargingStation
status: {}