apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:
  name: ngsi-ld-city-environmentbasemodel
  namespace: ktwin
spec:
  displayName: EnvironmentBaseModel
  extendsInterface: ngsi-ld-city-ngsildbasemodel
  id: ngsi-ld-city-environmentbasemodel
  properties:
  - name: dateObserved
    schema:
      primitiveType: dateTime
    writable: true
  - name: areaServed
    schema:
      primitiveType: string
    writable: true
  relationships:
  - maxMultiplicity: 1
    name: refPointOfInterest
    interface: ngsi-ld-city-pointofinterest
status: {}
---
# apiVersion: dtd.ktwin/v0
# kind: TwinInstance
# metadata:
#   name: ngsi-ld-city-environmentbasemodel-001
#   namespace: ktwin
# spec:
#   interface: ngsi-ld-city-environmentbasemodel
#   template:
#     metadata:
#     spec:
#       containers:
#       - image: dev.local/ktwin/edge-service:0.1
#         imagePullPolicy: IfNotPresent
#         name: ngsi-ld-city-environmentbasemodel-001
#         resources: {}
#   twinInstanceRelationships:
#   - name: refPointOfInterest-001
#     interface: ngsi-ld-city-pointofinterest-001
# status: {}
