apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-streetlight-001
  namespace: ktwin
spec:
  interface: ngsi-ld-city-streetlight
  twinInstanceRelationships:
  - name: refStreetlightModel-001
    interface: ngsi-ld-city-streetlightmodel-001
  - name: refStreetlightControlCabinet-001
    interface: ngsi-ld-city-streetlightcontrolcabinet-001
  - name: refDevice-001
    interface: ngsi-ld-city-device-001
  - name: refStreetlightGroup-001
    interface: ngsi-ld-city-streetlightgroup-001
status: {}
