apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:
  name: ngsi-ld-city-parkingspot
  namespace: ktwin
spec:
  displayName: ParkingSpot
  extendsInterface: ngsi-ld-city-ngsildbasemodel
  id: ngsi-ld-city-parkingspot
  properties:
  - name: dateObserved
    schema:
      primitiveType: double
    writable: true
  - name: width
    schema:
      primitiveType: double
    writable: true
  - name: length
    schema:
      primitiveType: double
    writable: true
  - name: timeInstant
    schema:
      primitiveType: dateTime
    writable: true
  - name: image
    schema:
      primitiveType: string
    writable: true
  - name: color
    schema:
      primitiveType: string
    writable: true
  - name: category
    schema:
      enumType:
        enumValues:
        - displayName: Offstreet
          enumValue: offStreet
          name: offStreet
        - displayName: OnStreet
          enumValue: onStreet
          name: onStreet
        valueSchema: string
    writable: true
  - name: status
    schema:
      enumType:
        enumValues:
        - displayName: Occupied
          enumValue: occupied
          name: occupied
        - displayName: Free
          enumValue: free
          name: free
        - displayName: Closed
          enumValue: closed
          name: closed
        - displayName: Unkown
          enumValue: unkown
          name: unkown
        valueSchema: string
  relationships:
  - maxMultiplicity: 1
    name: refParkingGroup
    interface: ngsi-ld-city-parkinggroup
  - maxMultiplicity: 1
    name: refOnStreetParking
    interface: ngsi-ld-city-onstreetparking
  - maxMultiplicity: 1
    name: refOffStreetParking
    interface: ngsi-ld-city-offstreetparking
  - maxMultiplicity: 1
    name: refdevice
    interface: ngsi-ld-city-device
status: {}
---
# apiVersion: dtd.ktwin/v0
# kind: TwinInstance
# metadata:
#   name: ngsi-ld-city-parkingspot-001
#   namespace: ktwin
# spec:
#   interface: ngsi-ld-city-parkingspot
#   template:
#     metadata:
    
#     spec:
#       containers:
#       - image: dev.local/ktwin/edge-service:0.1
#         imagePullPolicy: IfNotPresent
#         name: ngsi-ld-city-parkingspot-001
#         resources: {}
#   twinInstanceRelationships:
#   - name: refParkingGroup-001
#     interface: ngsi-ld-city-parkinggroup-001
#   - name: refOnStreetParking-001
#     interface: ngsi-ld-city-onstreetparking-001
#   - name: refOffStreetParking-001
#     interface: ngsi-ld-city-offstreetparking-001
#   - name: refdevice-001
#     interface: ngsi-ld-city-device-001
# status: {}
