apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:

  name: ngsi-ld-city-streetlightcontrolcabinet
  namespace: ktwin
spec:
  displayName: StreetlightControlCabinet
  extendsInterface: ngsi-ld-city-ngsildbasemodel
  id: ngsi-ld-city-streetlightcontrolcabinet
  properties:
  - name: serialNumber
    schema:
      primitiveType: string
    writable: true
  - name: brandName
    schema:
      primitiveType: string
    writable: true
  - name: modelName
    schema:
      primitiveType: string
    writable: true
  - name: manufacturerName
    schema:
      primitiveType: string
    writable: true
  - name: cupboardMadeOf
    schema:
      enumType:
        enumValues:
        - displayName: plastic
          enumValue: plastic
          name: plastic
        - displayName: metal
          enumValue: metal
          name: metal
        - displayName: concrete
          enumValue: concrete
          name: concrete
        - displayName: other
          enumValue: other
          name: other
        valueSchema: string
    writable: true
  - name: features
    schema:
      enumType:
        enumValues:
        - displayName: astronomicalClock
          enumValue: astronomicalClock
          name: astronomicalClock
        - displayName: individualControl
          enumValue: individualControl
          name: individualControl
        valueSchema: string
    writable: true
  - description: A list of standards to which the cabinet controller is compliant
      with (ex. IP54)
    name: compliantWith
    schema:
      primitiveType: string
  - description: A field reserved for annotations (incidences, remarks, etc.)
    name: annotations
    schema:
      primitiveType: string
  - name: dateServiceStarted
    schema:
      primitiveType: dateTime
    writable: true
  - name: dateLastProgramming
    schema:
      primitiveType: dateTime
    writable: true
  - name: nextActuationDeadline
    schema:
      primitiveType: dateTime
    writable: true
  - description: Responsible for the cabinet controller, i.e. entity in charge of
      actuating (programming, etc.).
    name: responsible
    schema:
      primitiveType: string
    writable: true
  - name: workingMode
    schema:
      enumType:
        enumValues:
        - displayName: automatic
          enumValue: automatic
          name: automatic
        - displayName: manual
          enumValue: manual
          name: manual
        - displayName: semiautomatic
          enumValue: semiautomatic
          name: semiautomatic
        valueSchema: string
    writable: true
  - description: The maximum power available (by contract) for the circuits controlled
      by this cabinet. Units:'Kilowatts (kW)'
    name: maximumPowerAvailable
    schema:
      primitiveType: double
    writable: true
  - description: Energy consumed by the circuits controlled since metering started
      (since dateMeteringStarted). Units:'Kilowatts per hour (kWh).
    name: energyConsumed
    schema:
      primitiveType: double
    writable: true
  - description: Cost of the energy consumed by the circuits controlled since the
      metering start date.
    name: energyCost
    schema:
      primitiveType: double
    writable: true
  - name: reactiveEnergyConsumed
    schema:
      primitiveType: double
    writable: true
  - name: dateMeteringStarted
    schema:
      primitiveType: dateTime
    writable: true
  - name: lastMeterReading
    schema:
      primitiveType: double
    writable: true
  - name: meterReadingPeriod
    schema:
      primitiveType: integer
    writable: true
  - name: frequency
    schema:
      primitiveType: integer
    writable: true
  - name: totalActivePower
    schema:
      primitiveType: double
    writable: true
  - name: totalReactivePower
    schema:
      primitiveType: double
    writable: true
  - name: activePowerR
    schema:
      primitiveType: double
    writable: true
  - name: activePowerS
    schema:
      primitiveType: double
    writable: true
  - name: activePowerT
    schema:
      primitiveType: double
    writable: true
  - name: reactivePowerR
    schema:
      primitiveType: double
    writable: true
  - name: reactivePowerS
    schema:
      primitiveType: double
    writable: true
  - name: reactivePowerT
    schema:
      primitiveType: double
    writable: true
  - name: powerFactorR
    schema:
      primitiveType: double
    writable: true
  - name: powerFactorS
    schema:
      primitiveType: double
    writable: true
  - name: powerFactorT
    schema:
      primitiveType: double
    writable: true
  - name: cosPhi
    schema:
      primitiveType: double
    writable: true
  - name: intensityR
    schema:
      primitiveType: double
    writable: true
  - name: intensityS
    schema:
      primitiveType: double
    writable: true
  - name: voltageR
    schema:
      primitiveType: double
    writable: true
  - name: voltageS
    schema:
      primitiveType: double
    writable: true
  - name: voltageT
    schema:
      primitiveType: double
    writable: true
  - name: thdrVoltageR
    schema:
      primitiveType: double
    writable: true
  - name: thdrVoltageS
    schema:
      primitiveType: double
    writable: true
  - name: thdrVoltageT
    schema:
      primitiveType: double
    writable: true
  - name: thdrIntensityR
    schema:
      primitiveType: double
    writable: true
  - name: thdrIntensityS
    schema:
      primitiveType: double
    writable: true
  - name: thdrIntensityT
    schema:
      primitiveType: double
    writable: true
  relationships:
  - description: Streetlight group(s) controlled. List of references to entities of
      type StreetlightGroup
    name: refStreetlightGroup
    interface: ngsi-ld-city-streetlightgroup
  - description: Reference to the device(s) used to monitor this control cabinet.
    name: refDevice
    interface: ngsi-ld-city-device
status: {}
---
# apiVersion: dtd.ktwin/v0
# kind: TwinInstance
# metadata:

#   name: ngsi-ld-city-streetlightcontrolcabinet-001
#   namespace: ktwin
# spec:
#   interface: ngsi-ld-city-streetlightcontrolcabinet
#   template:
#     metadata:
    
#     spec:
#       containers:
#       - image: dev.local/ktwin/edge-service:0.1
#         imagePullPolicy: IfNotPresent
#         name: ngsi-ld-city-streetlightcontrolcabinet-001
#         resources: {}
#   twinInstanceRelationships:
#   - name: refStreetlightGroup-001
#     interface: ngsi-ld-city-streetlightgroup-001
#   - name: refDevice-001
#     interface: ngsi-ld-city-device-001
# status: {}
