apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:
  name: ngsi-ld-city-ngsildbasemodel
  namespace: ktwin
spec:
  displayName: NGSILDBaseModel
  id: ngsi-ld-city-ngsildbasemodel
  properties:
  - name: dataProvider
    schema:
      primitiveType: string
    writable: true
  - name: dateModified
    schema:
      primitiveType: dateTime
    writable: true
  - name: dateCreated
    schema:
      primitiveType: dateTime
    writable: true
  - name: source
    schema:
      primitiveType: string
    writable: true
  - name: alternateName
    schema:
      primitiveType: string
    writable: true
  - name: name
    schema:
      primitiveType: string
    writable: true
  - name: description
    schema:
      primitiveType: string
    writable: true
  - name: owner
    schema:
      primitiveType: string
    writable: true
  - name: seeAlso
    schema:
      primitiveType: string
    writable: true
status: {}
#---
# apiVersion: dtd.ktwin/v0
# kind: TwinInstance
# metadata:
#   name: ngsi-ld-city-ngsildbasemodel-001
#   namespace: ktwin
# spec:
#   interface: ngsi-ld-city-ngsildbasemodel
#   template:
#     metadata:
#     spec:
#       containers:
#       - image: dev.local/ktwin/edge-service:0.1
#         imagePullPolicy: IfNotPresent
#         name: ngsi-ld-city-ngsildbasemodel-001
#         resources: {}
# status: {}
