apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:
  name: ngsi-ld-city-geolocation
  namespace: ktwin
spec:
  displayName: GeoLocation
  id: ngsi-ld-city-geolocation
  properties:
  - name: type
    schema:
      enumType:
        enumValues:
        - displayName: Position
          enumValue: Position
          name: position
        - displayName: Point
          enumValue: Point
          name: point
        - displayName: MultiPoint
          enumValue: MultiPoint
          name: multiPoint
        - displayName: LineString
          enumValue: LineString
          name: lineString
        - displayName: MultiLineString
          enumValue: MultiLineString
          name: multiLineString
        - displayName: Polygon
          enumValue: Polygon
          name: polygon
        - displayName: MultiPolygon
          enumValue: MultiPolygon
          name: multiPolygon
        valueSchema: string
    writable: true
  - name: coordinates
    schema:
      primitiveType: string
    writable: true
status: {}
---
# apiVersion: dtd.ktwin/v0
# kind: TwinInstance
# metadata:
#   name: ngsi-ld-city-geolocation-001
#   namespace: ktwin
# spec:
#   interface: ngsi-ld-city-geolocation
#   template:
#     metadata:
#     spec:
#       containers:
#       - image: dev.local/ktwin/edge-service:0.1
#         imagePullPolicy: IfNotPresent
#         name: ngsi-ld-city-geolocation-001
#         resources: {}
# status: {}
