apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:
  name: s4city-city-cityobject
  namespace: ktwin
spec:
  description: Generic class for describing city objects.
  displayName: City Object
  extendsInterface: geosparql-feature
  id: s4city-city-cityobject
status: {}
#---
# apiVersion: dtd.ktwin/v0
# kind: TwinInstance
# metadata:
#   name: s4city-city-cityobject-001
#   namespace: ktwin
# spec:
#   interface: s4city-city-cityobject
#   template:
#     metadata:
#     spec:
#       containers:
#       - image: dev.local/ktwin/edge-service:0.1
#         imagePullPolicy: IfNotPresent
#         name: s4city-city-cityobject-001
#         resources: {}
# status: {}
