apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:

  name: ngsi-ld-city-parkingmode
  namespace: ktwin
spec:
  displayName: ParkingMode
  id: ngsi-ld-city-parkingmode
  properties:
  - name: parkingMode
    schema:
      enumType:
        enumValues:
        - displayName: EchelonParking
          enumValue: echelonParking
          name: echelonParking
        - displayName: ParallelParking
          enumValue: parallelParking
          name: parallelParking
        - displayName: perpendicularParking
          enumValue: perpendicularParking
          name: perpendicularParking
        valueSchema: string
status: {}
---
# apiVersion: dtd.ktwin/v0
# kind: TwinInstance
# metadata:

#   name: ngsi-ld-city-parkingmode-001
#   namespace: ktwin
# spec:
#   interface: ngsi-ld-city-parkingmode
#   template:
#     metadata:
    
#     spec:
#       containers:
#       - image: dev.local/ktwin/edge-service:0.1
#         imagePullPolicy: IfNotPresent
#         name: ngsi-ld-city-parkingmode-001
#         resources: {}
# status: {}
