apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-airqualityobserved-001
  namespace: ktwin
spec:
  interface: ngsi-ld-city-airqualityobserved
  twinInstanceRelationships:
  - name: refDevice-001
    instance: ngsi-ld-city-device-001
    interface: ngsi-ld-city-device
  - name: refWeatherObserved-001
    instance: ngsi-ld-city-weatherobserved-001
    interface: ngsi-ld-city-weatherobserved
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-airqualityobserved-002
  namespace: ktwin
spec:
  interface: ngsi-ld-city-airqualityobserved
  twinInstanceRelationships:
  - name: refDevice-002
    instance: ngsi-ld-city-device-002
    interface: ngsi-ld-city-device
  - name: refWeatherObserved-002
    instance: ngsi-ld-city-weatherobserved-002
    interface: ngsi-ld-city-weatherobserved
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-airqualityobserved-003
  namespace: ktwin
spec:
  interface: ngsi-ld-city-airqualityobserved
  twinInstanceRelationships:
  - name: refDevice-003
    instance: ngsi-ld-city-device-003
    interface: ngsi-ld-city-device
  - name: refWeatherObserved-003
    instance: ngsi-ld-city-weatherobserved-003
    interface: ngsi-ld-city-weatherobserved
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-airqualityobserved-004
  namespace: ktwin
spec:
  interface: ngsi-ld-city-airqualityobserved
  twinInstanceRelationships:
  - name: refDevice-004
    instance: ngsi-ld-city-device-004
    interface: ngsi-ld-city-device
  - name: refWeatherObserved-004
    instance: ngsi-ld-city-weatherobserved-004
    interface: ngsi-ld-city-weatherobserved
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-airqualityobserved-005
  namespace: ktwin
spec:
  interface: ngsi-ld-city-airqualityobserved
  twinInstanceRelationships:
  - name: refDevice-005
    instance: ngsi-ld-city-device-005
    interface: ngsi-ld-city-device
  - name: refWeatherObserved-005
    instance: ngsi-ld-city-weatherobserved-005
    interface: ngsi-ld-city-weatherobserved
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-airqualityobserved-006
  namespace: ktwin
spec:
  interface: ngsi-ld-city-airqualityobserved
  twinInstanceRelationships:
  - name: refDevice-006
    instance: ngsi-ld-city-device-006
    interface: ngsi-ld-city-device
  - name: refWeatherObserved-006
    instance: ngsi-ld-city-weatherobserved-006
    interface: ngsi-ld-city-weatherobserved
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-airqualityobserved-007
  namespace: ktwin
spec:
  interface: ngsi-ld-city-airqualityobserved
  twinInstanceRelationships:
  - name: refDevice-007
    instance: ngsi-ld-city-device-007
    interface: ngsi-ld-city-device
  - name: refWeatherObserved-007
    instance: ngsi-ld-city-weatherobserved-007
    interface: ngsi-ld-city-weatherobserved
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-airqualityobserved-008
  namespace: ktwin
spec:
  interface: ngsi-ld-city-airqualityobserved
  twinInstanceRelationships:
  - name: refDevice-008
    instance: ngsi-ld-city-device-008
    interface: ngsi-ld-city-device
  - name: refWeatherObserved-008
    instance: ngsi-ld-city-weatherobserved-008
    interface: ngsi-ld-city-weatherobserved
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-airqualityobserved-009
  namespace: ktwin
spec:
  interface: ngsi-ld-city-airqualityobserved
  twinInstanceRelationships:
  - name: refDevice-009
    instance: ngsi-ld-city-device-009
    interface: ngsi-ld-city-device
  - name: refWeatherObserved-009
    instance: ngsi-ld-city-weatherobserved-009
    interface: ngsi-ld-city-weatherobserved
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-airqualityobserved-010
  namespace: ktwin
spec:
  interface: ngsi-ld-city-airqualityobserved
  twinInstanceRelationships:
  - name: refDevice-010
    instance: ngsi-ld-city-device-010
    interface: ngsi-ld-city-device
  - name: refWeatherObserved-010
    instance: ngsi-ld-city-weatherobserved-010
    interface: ngsi-ld-city-weatherobserved
status: {}
