apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-offstreet-parkingspot-001
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refParkingGroup-001
    instance: ngsi-ld-city-parkinggroup-001
    interface: ngsi-ld-city-parkinggroup
  - name: refOnStreetParking-001
    instance: ngsi-ld-city-onstreetparking-001
    interface: ngsi-ld-city-onstreetparking
  - name: refOffStreetParking-001
    instance: ngsi-ld-city-offstreetparking-001
    interface: ngsi-ld-city-offstreetparking
  - name: refdevice-001
    instance: ngsi-ld-city-device
    interface: ngsi-ld-city-device-001
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-offstreet-parkingspot-002
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refParkingGroup-002
    instance: ngsi-ld-city-parkinggroup-002
    interface: ngsi-ld-city-parkinggroup
  - name: refOnStreetParking-002
    instance: ngsi-ld-city-onstreetparking-002
    interface: ngsi-ld-city-onstreetparking
  - name: refOffStreetParking-002
    instance: ngsi-ld-city-offstreetparking-002
    interface: ngsi-ld-city-offstreetparking
  - name: refdevice-002
    instance: ngsi-ld-city-device
    interface: ngsi-ld-city-device-002
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-offstreet-parkingspot-003
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refParkingGroup-003
    instance: ngsi-ld-city-parkinggroup-003
    interface: ngsi-ld-city-parkinggroup
  - name: refOnStreetParking-003
    instance: ngsi-ld-city-onstreetparking-003
    interface: ngsi-ld-city-onstreetparking
  - name: refOffStreetParking-003
    instance: ngsi-ld-city-offstreetparking-003
    interface: ngsi-ld-city-offstreetparking
  - name: refdevice-003
    instance: ngsi-ld-city-device
    interface: ngsi-ld-city-device-003
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-offstreet-parkingspot-004
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refParkingGroup-004
    instance: ngsi-ld-city-parkinggroup-004
    interface: ngsi-ld-city-parkinggroup
  - name: refOnStreetParking-004
    instance: ngsi-ld-city-onstreetparking-004
    interface: ngsi-ld-city-onstreetparking
  - name: refOffStreetParking-004
    instance: ngsi-ld-city-offstreetparking-004
    interface: ngsi-ld-city-offstreetparking
  - name: refdevice-004
    instance: ngsi-ld-city-device
    interface: ngsi-ld-city-device-004
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-offstreet-parkingspot-005
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refParkingGroup-005
    instance: ngsi-ld-city-parkinggroup-005
    interface: ngsi-ld-city-parkinggroup
  - name: refOnStreetParking-005
    instance: ngsi-ld-city-onstreetparking-005
    interface: ngsi-ld-city-onstreetparking
  - name: refOffStreetParking-005
    instance: ngsi-ld-city-offstreetparking-005
    interface: ngsi-ld-city-offstreetparking
  - name: refdevice-005
    instance: ngsi-ld-city-device
    interface: ngsi-ld-city-device-005
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-offstreet-parkingspot-006
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refParkingGroup-006
    instance: ngsi-ld-city-parkinggroup-006
    interface: ngsi-ld-city-parkinggroup
  - name: refOnStreetParking-006
    instance: ngsi-ld-city-onstreetparking-006
    interface: ngsi-ld-city-onstreetparking
  - name: refOffStreetParking-006
    instance: ngsi-ld-city-offstreetparking-006
    interface: ngsi-ld-city-offstreetparking
  - name: refdevice-006
    instance: ngsi-ld-city-device
    interface: ngsi-ld-city-device-006
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-offstreet-parkingspot-007
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refParkingGroup-007
    instance: ngsi-ld-city-parkinggroup-007
    interface: ngsi-ld-city-parkinggroup
  - name: refOnStreetParking-007
    instance: ngsi-ld-city-onstreetparking-007
    interface: ngsi-ld-city-onstreetparking
  - name: refOffStreetParking-007
    instance: ngsi-ld-city-offstreetparking-007
    interface: ngsi-ld-city-offstreetparking
  - name: refdevice-007
    instance: ngsi-ld-city-device
    interface: ngsi-ld-city-device-007
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-offstreet-parkingspot-008
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refParkingGroup-008
    instance: ngsi-ld-city-parkinggroup-008
    interface: ngsi-ld-city-parkinggroup
  - name: refOnStreetParking-008
    instance: ngsi-ld-city-onstreetparking-008
    interface: ngsi-ld-city-onstreetparking
  - name: refOffStreetParking-008
    instance: ngsi-ld-city-offstreetparking-008
    interface: ngsi-ld-city-offstreetparking
  - name: refdevice-008
    instance: ngsi-ld-city-device
    interface: ngsi-ld-city-device-008
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-offstreet-parkingspot-009
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refParkingGroup-009
    instance: ngsi-ld-city-parkinggroup-009
    interface: ngsi-ld-city-parkinggroup
  - name: refOnStreetParking-009
    instance: ngsi-ld-city-onstreetparking-009
    interface: ngsi-ld-city-onstreetparking
  - name: refOffStreetParking-009
    instance: ngsi-ld-city-offstreetparking-009
    interface: ngsi-ld-city-offstreetparking
  - name: refdevice-009
    instance: ngsi-ld-city-device
    interface: ngsi-ld-city-device-009
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-offstreet-parkingspot-010
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refParkingGroup-010
    instance: ngsi-ld-city-parkinggroup-010
    interface: ngsi-ld-city-parkinggroup
  - name: refOnStreetParking-010
    instance: ngsi-ld-city-onstreetparking-010
    interface: ngsi-ld-city-onstreetparking
  - name: refOffStreetParking-010
    instance: ngsi-ld-city-offstreetparking-010
    interface: ngsi-ld-city-offstreetparking
  - name: refdevice-010
    instance: ngsi-ld-city-device
    interface: ngsi-ld-city-device-010
status: {}
---