apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-onstreetparkingspot-nb001-onp0001-s0001
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refOnStreetParking
    instance: ngsi-ld-city-onstreetparking-nb001-onp0001
    interface: ngsi-ld-city-onstreetparking
  - name: refdevice
    instance: ngsi-ld-city-device-nb001-onp0001-s0001
    interface: ngsi-ld-city-device
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-onstreetparkingspot-nb001-onp0001-s0002
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refOnStreetParking
    instance: ngsi-ld-city-onstreetparking-nb001-onp0001
    interface: ngsi-ld-city-onstreetparking
  - name: refdevice
    instance: ngsi-ld-city-device-nb001-onp0001-s0002
    interface: ngsi-ld-city-device
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-onstreetparkingspot-nb001-onp0001-s0003
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refOnStreetParking
    instance: ngsi-ld-city-onstreetparking-nb001-onp0001
    interface: ngsi-ld-city-onstreetparking
  - name: refdevice
    instance: ngsi-ld-city-device-nb001-onp0001-s0003
    interface: ngsi-ld-city-device
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-onstreetparkingspot-nb001-onp0001-s0004
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refOnStreetParking
    instance: ngsi-ld-city-onstreetparking-nb001-onp0001
    interface: ngsi-ld-city-onstreetparking
  - name: refdevice
    instance: ngsi-ld-city-device-nb001-onp0001-s0004
    interface: ngsi-ld-city-device
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-onstreetparkingspot-nb001-onp0001-s0005
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refOnStreetParking
    instance: ngsi-ld-city-onstreetparking-nb001-onp0001
    interface: ngsi-ld-city-onstreetparking
  - name: refdevice
    instance: ngsi-ld-city-device-nb001-onp0001-s0005
    interface: ngsi-ld-city-device
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-onstreetparkingspot-nb001-onp0001-s0006
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refOnStreetParking
    instance: ngsi-ld-city-onstreetparking-nb001-onp0001
    interface: ngsi-ld-city-onstreetparking
  - name: refdevice
    instance: ngsi-ld-city-device-nb001-onp0001-s0006
    interface: ngsi-ld-city-device
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-onstreetparkingspot-nb001-onp0001-s0007
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refOnStreetParking
    instance: ngsi-ld-city-onstreetparking-nb001-onp0001
    interface: ngsi-ld-city-onstreetparking
  - name: refdevice
    instance: ngsi-ld-city-device-nb001-onp0001-s0007
    interface: ngsi-ld-city-device
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-onstreetparkingspot-nb001-onp0001-s0008
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refOnStreetParking
    instance: ngsi-ld-city-onstreetparking-nb001-onp0001
    interface: ngsi-ld-city-onstreetparking
  - name: refdevice
    instance: ngsi-ld-city-device-nb001-onp0001-s0008
    interface: ngsi-ld-city-device
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-onstreetparkingspot-nb001-onp0001-s0009
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refOnStreetParking
    instance: ngsi-ld-city-onstreetparking-nb001-onp0001
    interface: ngsi-ld-city-onstreetparking
  - name: refdevice
    instance: ngsi-ld-city-device-nb001-onp0001-s0009
    interface: ngsi-ld-city-device
status: {}
---
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-onstreetparkingspot-nb001-onp0001-s0010
  namespace: ktwin
spec:
  interface: ngsi-ld-city-parkingspot
  twinInstanceRelationships:
  - name: refOnStreetParking
    instance: ngsi-ld-city-onstreetparking-nb001-onp0001
    interface: ngsi-ld-city-onstreetparking
  - name: refdevice
    instance: ngsi-ld-city-device-nb001-onp0001-s0010
    interface: ngsi-ld-city-device
status: {}
