apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:

  name: geosparql-feature
  namespace: ktwin
spec:
  description: This class represents the top-level feature type. This class is equivalent
    to GFI_Feature defined in ISO 19156:2011, and it is superclass of all feature
    types. GeoSPARQL 1.0 is an OGC Standard.Copyright (c) 2012 Open Geospatial Consortium.
  displayName: Feature
  extendsInterface: geosparql-spatialobject
  id: geosparql-feature
  relationships:
  - name: hasGeometry
    interface: geosparql-geometry
status: {}
---
# apiVersion: dtd.ktwin/v0
# kind: TwinInstance
# metadata:

#   name: geosparql-feature-001
#   namespace: ktwin
# spec:
#   interface: geosparql-feature
#   template:
#     metadata:
    
#     spec:
#       containers:
#       - image: dev.local/ktwin/edge-service:0.1
#         imagePullPolicy: IfNotPresent
#         name: geosparql-feature-001
#         resources: {}
#   twinInstanceRelationships:
#   - name: hasGeometry-001
#     interface: geosparql-geometry-001
# status: {}
