apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:
  name: ngsi-ld-city-onstreetparking
  namespace: ktwin
spec:
  displayName: OnStreetParking
  extendsInterface: ngsi-ld-city-ngsildbasemodel
  id: ngsi-ld-city-onstreetparking
  properties:
  - name: category
    schema:
      enumType:
        enumValues:
        - displayName: BlueZone
          enumValue: blueZone
          name: blueZone
        - displayName: FeeCharged
          enumValue: feeCharged
          name: feeCharged
        - displayName: ForDisabled
          enumValue: forDisabled
          name: forDisabled
        - displayName: ForElectricalCharging
          enumValue: forElectricalCharging
          name: forElectricalCharging
        - displayName: ForLoadUnload
          enumValue: forLoadUnload
          name: forLoadUnload
        - displayName: ForResidents
          enumValue: forResidents
          name: forResidents
        - displayName: Free
          enumValue: free
          name: free
        - displayName: GreenZone
          enumValue: greenZone
          name: greenZone
        - displayName: MediumTerm
          enumValue: mediumTerm
          name: mediumTerm
        - displayName: OnlyWithPermit
          enumValue: onlyWithPermit
          name: onlyWithPermit
        - displayName: ShortTerm
          enumValue: shortTerm
          name: shortTerm
        - displayName: TaxiStop
          enumValue: taxiStop
          name: taxiStop
        valueSchema: string
    writable: true
  - name: usageScenario
    schema:
      enumType:
        enumValues:
        - displayName: CarSharing
          enumValue: carSharing
          name: carSharing
        - displayName: DropOff
          enumValue: dropOff
          name: dropOff
        - displayName: KissAndRide
          enumValue: kissAndRide
          name: kissAndRide
        - displayName: LiftShare
          enumValue: liftShare
          name: liftShare
        - displayName: LoadingBay
          enumValue: loadingBay
          name: loadingBay
        - displayName: OvernightParking
          enumValue: overnightParking
          name: overnightParking
        - displayName: ParkAndRide
          enumValue: parkAndRide
          name: parkAndRide
        - displayName: ParkAndCycle
          enumValue: parkAndCycle
          name: parkAndCycle
        - displayName: ParkAndWalk
          enumValue: parkAndWalk
          name: parkAndWalk
        - displayName: VehicleLift
          enumValue: vehicleLift
          name: vehicleLift
        valueSchema: string
    writable: true
  - name: maximumAllowedStay
    schema:
      primitiveType: string
    writable: true
  relationships:
  - name: refParkingGroup
    interface: ngsi-ld-city-parkinggroup
  - name: refParkingSpot
    interface: ngsi-ld-city-parkingspot
status: {}
