apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:

  name: ngsi-ld-city-boatauthorized
  namespace: ktwin
spec:
  comment: 'Original source: https://github.com/smart-data-models/dataModel.Ports/blob/master/BoatAuthorized/doc/spec.md'
  description: The data model is intended to provide information on the boats authorized
    to operate within the port according to the ISO 8666 standard for Boat Category.
    This repository is created by type of category of boat (pleasure craft, trade,
    passengers, ...). For each type of category, a list of optional subtypes of category
    can be associated.
  displayName: Boat Authorized
  extendsInterface: ngsi-ld-city-ngsildbasemodel
  id: ngsi-ld-city-boatauthorized
  properties:
  - comment: Required property
    description: A unique value of the list. Enum:'cargo, fishing, historic, passenger,
      specialist, Tanker, war, yachting'
    displayName: Boat type
    name: boatType
    schema:
      enumType:
        enumValues:
        - displayName: Cargo
          enumValue: cargo
          name: cargo
        - displayName: Fishing
          enumValue: fishing
          name: fishing
        - displayName: Historic
          enumValue: historic
          name: historic
        - displayName: Passenger
          enumValue: passenger
          name: passenger
        - displayName: Specialist
          enumValue: specialist
          name: specialist
        - displayName: Tanker
          enumValue: Tanker
          name: tanker
        - displayName: War
          enumValue: war
          name: war
        - displayName: Yachting
          enumValue: yachting
          name: yachting
        valueSchema: string
  - comment: Required property. Since DTDLv2 doesn't support arrays for Properties,
      a single string will be used. Attention. Not all enum values are listed in the
      description
    description: Sub Type for a boatType. A combination of the elements 'aircraftCarrier,
      amphibiousAssaultShip, anchorHandlingVessel, artisanVessel, bac, barge, bargeCarrier,
      bulkCarrier, buoyTenderBoat, butaneCarrier, cableLayer, canoe, caravel, cargoCarrier,
      carrack, catamaran, chemicalCarrier, clipper, coastalFerry, cog, containerCarrier,
      corvette, craneBarge, crudeCarrier, cruise, cruiser, destroyer, dhow, divingVessel,
      djong, dredger, drifter, drillRig, factoryShip, ferry, fireBoat, fisheriesResearchVessel,...'
    displayName: Boat subtype
    name: boatSubType
    schema:
      primitiveType: string
  - comment: Required property
    description: Last time data were gathered
    displayName: Last reported date
    name: dateLastReported
    schema:
      primitiveType: dateTime
    writable: true
  - description: The geographic area where a service or offered item is provided
    displayName: Area served
    name: areaServed
    schema:
      primitiveType: string
    writable: true
  - description: Maximum draft allowed to access the harbor. The unit code (text)
      is given using the UN/CEFACT Common Codes . For instance, MTR represents Meter
    displayName: Maximum draft allowed
    name: maxDraft
    schema:
      primitiveType: double
    writable: true
  - description: Maximum length allowed to access the harbor. The unit code (text)
      is given using the UN/CEFACT Common Codes. For instance, MTR represents Meter
    displayName: Maximum length allowed
    name: maxLength
    schema:
      primitiveType: double
    writable: true
  - description: Minimum length allowed to access the harbor. The unit code (text)
      is given using the UN/CEFACT Common Codes. For instance, MTR represents Meter
    displayName: Minimum Length
    name: minLength
    schema:
      primitiveType: double
    writable: true
  - description: Maximum width allowed to access the harbor. The unit code (text)
      is given using the UN/CEFACT Common Codes . For instance, MTR represents Meter
    displayName: Maximum width allowed
    name: maxWidth
    schema:
      primitiveType: double
    writable: true
  - description: Maximum tonnage authorized to access the harbor. The unit code (text)
      is given using the UN/CEFACT Common Codes . For instance, TNE represents Tonne
      Metric
    displayName: Maximum Tonnage
    name: maxTonnage
    schema:
      primitiveType: double
    writable: true
  relationships:
  - comment: Required relationship
    description: Port that belongs to
    displayName: belongs to
    maxMultiplicity: 1
    name: refSeaPort
    interface: ngsi-ld-city-seaportfacilities
  - description: Point of Interest that the element has relation to
    displayName: related to
    maxMultiplicity: 1
    name: refPointOfInterest
    interface: ngsi-ld-city-pointofinterest
status: {}
---
# apiVersion: dtd.ktwin/v0
# kind: TwinInstance
# metadata:

#   name: ngsi-ld-city-boatauthorized-001
#   namespace: ktwin
# spec:
#   interface: ngsi-ld-city-boatauthorized
#   template:
#     metadata:
    
#     spec:
#       containers:
#       - image: dev.local/ktwin/edge-service:0.1
#         imagePullPolicy: IfNotPresent
#         name: ngsi-ld-city-boatauthorized-001
#         resources: {}
#   twinInstanceRelationships:
#   - name: refSeaPort-001
#     interface: ngsi-ld-city-seaportfacilities-001
#   - name: refPointOfInterest-001
#     interface: ngsi-ld-city-pointofinterest-001
# status: {}
