apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:
  name: ngsi-ld-city-boatplacepricing
  namespace: ktwin
spec:
  comment: No official specification available yet
  description: 'Global description: Work in progress for boat place pricing. Bases
    on sample at https://github.com/smart-data-models/dataModel.Ports/blob/master/BoatPlacesPricing/examples/example.json'
  displayName: Boat Place pricing
  extendsInterface: ngsi-ld-city-ngsildbasemodel
  id: ngsi-ld-city-boatplacepricing
  properties:
  - description: The geographic area where a service or offered item is provided
    displayName: Area served
    name: areaServed
    schema:
      primitiveType: string
    writable: true
  - comment: Required property
    description: The date and time of this report in ISO8601 UTC format. It can be
      represented by a specific time instant or by an ISO8601 interval
    displayName: Date last reported
    name: dateLastReported
    schema:
      primitiveType: dateTime
    writable: true
  - comment: Required property. Since DTDLv2 doesn't support arrays for Properties,
      a single string will be used.
    description: 'List from the lowest to the highest categories: A combination of
      the items listed. Enum:''A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q,
      R, S, T1, T2, U, V, W, X, Y, Z, Z01, Z02, Z03, Z04, Z05, Z06, Z07, Z08, Z08,
      Z09, Z10, Z11, Z12, Z13, Z14, Z15, Z16, Z17'''
    displayName: Spot category range
    name: spotCategoryRange
    schema:
      primitiveType: string
    writable: true
  - description: Maximum draft allowed to access the harbor. The unit code (text)
      is given using the UN/CEFACT Common Codes . For instance, MTR represents Meter
    displayName: Maximum draft allowed
    name: maxDraft
    schema:
      primitiveType: double
    writable: true
  - description: Maximum length allowed to access the harbor. The unit code (text)
      is given using the UN/CEFACT Common Codes. For instance, MTR represents Meter
    displayName: Maximum length allowed
    name: maxLength
    schema:
      primitiveType: double
    writable: true
  - description: Minimum length allowed to access the harbor. The unit code (text)
      is given using the UN/CEFACT Common Codes. For instance, MTR represents Meter
    displayName: Minimum Length
    name: minLength
    schema:
      primitiveType: double
    writable: true
  - description: Maximum width allowed to access the harbor. The unit code (text)
      is given using the UN/CEFACT Common Codes . For instance, MTR represents Meter
    displayName: Maximum width allowed
    name: maxWidth
    schema:
      primitiveType: double
    writable: true
  - comment: Required property
    displayName: Valid from
    name: validFrom
    schema:
      primitiveType: dateTime
    writable: true
  - comment: Required property
    displayName: Valid through
    name: validThrough
    schema:
      primitiveType: dateTime
    writable: true
  - description: 'Property. Model:''https://schema.org/DateTime''. Type of period
      defined the date From and Through: A free text or a unique value of the different
      combination allowed ''season / offSeason'' - ''summer / winter'' - ''low / medium
      / high''. enum:''high, low, medium, offSeason, season, summer, winter'''
    displayName: Period
    name: period
    schema:
      primitiveType: string
    writable: true
  relationships:
  - comment: Required relationship
    description: Port that belongs to
    displayName: belongs to
    maxMultiplicity: 1
    name: refSeaPort
    interface: ngsi-ld-city-seaportfacilities
  - description: Point of Interest that the element has relation to
    displayName: related to
    maxMultiplicity: 1
    name: refPointOfInterest
    interface: ngsi-ld-city-pointofinterest
status: {}
---
# apiVersion: dtd.ktwin/v0
# kind: TwinInstance
# metadata:
#   name: ngsi-ld-city-boatplacepricing-001
#   namespace: ktwin
# spec:
#   interface: ngsi-ld-city-boatplacepricing
#   template:
#     metadata:
#     spec:
#       containers:
#       - image: dev.local/ktwin/edge-service:0.1
#         imagePullPolicy: IfNotPresent
#         name: ngsi-ld-city-boatplacepricing-001
#         resources: {}
#   twinInstanceRelationships:
#   - name: refSeaPort-001
#     interface: ngsi-ld-city-seaportfacilities-001
#   - name: refPointOfInterest-001
#     interface: ngsi-ld-city-pointofinterest-001
# status: {}
