apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-offstreetparking-nb001-ofp0001
  namespace: ktwin
spec:
  interface: ngsi-ld-city-offstreetparking
  twinInstanceRelationships:
  - name: refParkingGroup-nb001-ofp0001
    instance: ngsi-ld-city-parkinggroup-nb001-ofp0001
    interface: ngsi-ld-city-parkinggroup