apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:
  name: ngsi-ld-city-evchargingstation
  namespace: ktwin
spec:
  eventStore:
    persistRealEvent: true
    persistVirtualEvent: true
  description: EV Charging Station
  displayName: EV Charging Station
  extendsInterface: ngsi-ld-city-ngsildbasemodel
  id: ngsi-ld-city-evchargingstation
  properties:
  - description: The total number of vehicles which can be charged at the same time.
      The total number of sockets can be higher.
    name: capacity
    schema:
      primitiveType: integer
    writable: true
  - description: The total number of sockets offered by this charging station.
    name: socketNumber
    schema:
      primitiveType: integer
    writable: true
  - description: The number of vehicles which currently can be charged.
    name: availableCapacity
    schema:
      primitiveType: integer
    writable: true
  - description: 'Vehicle type(s) which can be charged. Model:''http://schema.org/Text''.
      Enum:''bicycle, bus, car, caravan, motorcycle, motorscooter, truck'' '
    name: allowedVehicleType
    schema:
      enumType:
        enumValues:
        - displayName: bicycle
          enumValue: bicycle
          name: bicycle
        - displayName: bus
          enumValue: bus
          name: bus
        - displayName: car
          enumValue: car
          name: car
        - displayName: caravan
          enumValue: caravan
          name: caravan
        - displayName: motorcycle
          enumValue: motorcycle
          name: motorcycle
        - displayName: motorscooter
          enumValue: motorscooter
          name: motorscooter
        - displayName: truck
          enumValue: truck
          name: truck
        valueSchema: string
  - description: The type of sockets offered by this station. Model:'http://schema.org/Text'.
      Enum:'Caravan_Mains_Socket, CHAdeMO, CCS/SAE, Dual_CHAdeMO, Dual_J-1772, Dual_Mennekes,
      J-1772, Mennekes, Other, Tesla, Type2, Type3, Wall_Euro'
    name: socketType
    schema:
      enumType:
        enumValues:
        - displayName: Caravan_Mains_Socket
          enumValue: Caravan_Mains_Socket
          name: caravan_Mains_Socket
        - displayName: CHAdeMO
          enumValue: CHAdeMO
          name: CHAdeMO
        - displayName: CCSSAE
          enumValue: CCSSAE
          name: CCSSAE
        - displayName: Dual_CHAdeMO
          enumValue: DualCHAdeMO
          name: DualCHAdeMO
        - displayName: Dual_J-1772
          enumValue: DualJ1772
          name: DualJ1772
        - displayName: Dual_Mennekes
          enumValue: DualMennekes
          name: DualMennekes
        - displayName: J-1772
          enumValue: J1772
          name: J1772
        - displayName: Mennekes
          enumValue: Mennekes
          name: Mennekes
        - displayName: Other
          enumValue: Other
          name: other
        - displayName: Tesla
          enumValue: Tesla
          name: Tesla
        - displayName: Type2
          enumValue: Type2
          name: type2
        - displayName: Type3
          enumValue: Type3
          name: type3
        - displayName: Wall_Euro
          enumValue: WallEuro
          name: WallEuro
        valueSchema: string
  - description: The opening hours of the charging station.
    name: openingHours
    schema:
      primitiveType: string
    writable: true
  - description: Model:'http://schema.org/Text'. Status of the charging station. Enum:'almostEmpty,
      almostFull, empty, full, outOfService, withIncidence, working'. Or any other
      application-specific.
    name: status
    schema:
      enumType:
        enumValues:
        - displayName: almostEmpty
          enumValue: almostEmpty
          name: almostEmpty
        - displayName: almostFull
          enumValue: almostFull
          name: almostFull
        - displayName: empty
          enumValue: empty
          name: empty
        - displayName: full
          enumValue: full
          name: full
        - displayName: outOfService
          enumValue: outOfService
          name: outOfService
        - displayName: withIncidence
          enumValue: withIncidence
          name: withIncidence
        - displayName: working
          enumValue: working
          name: working
        valueSchema: string
    writable: true
  - description: The name of the Network, with that the operator cooperates. Model:'https://schema.org/Text'.
    name: network
    schema:
      primitiveType: string
    writable: true
  - description: Charging station's operator. Model:'https://schema.org/Text'.
    name: operator
    schema:
      primitiveType: string
    writable: true
  - description: The total amperage offered by the charging station. Units:'Ampers
      (A)'
    name: amperage
    schema:
      primitiveType: double
    writable: true
  - description: The total voltage offered by the charging station. Units:'Volts (V)'
    name: voltage
    schema:
      primitiveType: double
    writable: true
  - description: 'Vehicle type(s) which can be charged. Model:''http://schema.org/Text''.
      Enum:''bicycle, bus, car, caravan, motorcycle, motorscooter, truck'' '
    name: chargeType
    schema:
      enumType:
        enumValues:
        - displayName: annualPayment
          enumValue: annualPayment
          name: annualPayment
        - displayName: flat
          enumValue: flat
          name: flat
        - displayName: free
          enumValue: free
          name: free
        - displayName: monthlyPayment
          enumValue: monthlyPayment
          name: monthlyPayment
        - displayName: other
          enumValue: other
          name: other
        valueSchema: string
  - description: Type(s) of charge when using this station. Model:'https://schema.org/Text'.
      Enum:'ByBankTransferInAdvance, ByInvoice, Cash, CheckInAdvance, COD, DirectDebit,
      GoogleCheckout, PayPal, PaySwarm'
    name: acceptedPaymentMethod
    schema:
      enumType:
        enumValues:
        - displayName: ByBankTransferInAdvance
          enumValue: ByBankTransferInAdvance
          name: byBankTransferInAdvance
        - displayName: ByInvoice
          enumValue: ByInvoice
          name: byInvoice
        - displayName: Cash
          enumValue: Cash
          name: cash
        - displayName: CheckInAdvance
          enumValue: CheckInAdvance
          name: checkInAdvance
        - displayName: COD
          enumValue: COD
          name: COD
        - displayName: DirectDebit
          enumValue: DirectDebit
          name: directDebit
        - displayName: GoogleCheckout
          enumValue: GoogleCheckout
          name: GoogleCheckout
        - displayName: PayPal
          enumValue: PayPal
          name: PayPal
        - displayName: PaySwarm
          enumValue: PaySwarm
          name: PaySwarm
        valueSchema: string
status: {}
