apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:
  name: ngsi-ld-city-airqualitylevel
  namespace: ktwin
spec:
  displayName: AirQualityLevel
  id: ngsi-ld-city-airqualitylevel
  properties:
  - name: level
    schema:
      enumType:
        enumValues:
        - displayName: Good
          enumValue: good
          name: good
        - displayName: Moderate
          enumValue: moderate
          name: moderate
        - displayName: UnhealthyForSensitiveGroups
          enumValue: unhealthyForSensitiveGroups
          name: unhealthyForSensitiveGroups
        - displayName: Unhealthy
          enumValue: unhealthy
          name: unhealthy
        - displayName: VeryUnhealthy
          enumValue: veryUnhealthy
          name: veryUnhealthy
        - displayName: Hazardous
          enumValue: hazardous
          name: hazardous
        valueSchema: string
status: {}
