apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:
  name: ngsi-ld-city-museum
  namespace: ktwin
spec:
  comment: 'Original source: https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/Museum/doc/spec.md'
  description: 'Global description: A museum'
  displayName: Museum
  extendsInterface: ngsi-ld-city-ngsildbasemodel
  id: ngsi-ld-city-museum
  properties:
  - description: The geographic area where a service or offered item is provided
    displayName: Area served
    name: areaServed
    schema:
      primitiveType: string
    writable: true
  - comment: Since DTDLv2 doesn't support arrays for Properties, a single string will
      be used.
    description: Allowed values:-Those defined by Wikipedia.- Any other extended value
      needed by an application and not described by the above resource.
    displayName: Art period
    name: artPeriod
    schema:
      primitiveType: string
    writable: true
  - comment: Since DTDLv2 doesn't support arrays for Properties, a single string will
      be used. Attention. Not all enum values are listed in the description
    description: Type of building that hosts the museum. Enum:'prehistoricPlace, acropolis,
      alcazaba,aqueduct, alcazar, amphitheatre, arch, polularArchitecture,basilica,
      road, chapel, cartuja, nobleHouse, residence,castle, castro, catacombs, cathedral,
      cloister, convent,prehistoricCave, dolmen, officeBuilding, houseBuilding,industrialBuilding,
      militaryBuilding, hermitage, fortress,sculpturalGroups, church, garden, fishMarket,
      masia,masiaFortificada, minaret, monastery, monolith, walls,necropolis, menhir,
      mansion, ...'
    displayName: Building type
    name: buildingType
    schema:
      primitiveType: string
    writable: true
  - description: Describes different facilities offered by this museum. Enum:'elevator,
      cafeteria, shop, auditory,conferenceRoom, audioguide, cloakRoom, forDisabled,
      forBabies,guidedTour, restaurant, ramp, reservation'. or any other value needed
      by an application.
    displayName: Facilities
    name: facilities
    schema:
      primitiveType: string
    writable: true
  - comment: Since DTDLv2 doesn't support arrays for Properties, a single string will
      be used. Attention. Not all enum values are listed in the description
    description: Main featured artist(s) at this museum.
    displayName: Featured artist
    name: featuredArtist
    schema:
      primitiveType: string
    writable: true
  - description: An ISO8601 time interval. For example 1920/1940. The second element
      of the interval can be left empty to denote 'till now'. A comma separated list
      of years, for instance 1620,1625,1718. - A century, represented by a year pattern,
      for instance 19xx would correspond to the twentieth century. And 196x would
      correspond to the sixties decade.
    displayName: Historical period
    name: historicalPeriod
    schema:
      primitiveType: string
    writable: true
  - comment: Since DTDLv2 doesn't support arrays for Properties, a single string will
      be used. Attention. Not all enum values are listed in the description
    description: Type of museum according to the exhibited content. Enum:'appliedArts,
      scienceAndTechnology, fineArts,music, history, sacredArt, archaeology, specials,decorativeArts,
      literature, medicineAndPharmacy, maritime,transports, military, wax, popularArtsAndTraditions,numismatic,
      unesco, ceramics, sumptuaryArts, naturalScience,prehistoric, ethnology, railway,
      mining, textile, sculpture,multiDisciplinar, painting, paleonthology, modernArt,thematic,
      architecture, museumHouse, cathedralMuseum,...'
    displayName: Museum type
    name: museumType
    schema:
      primitiveType: string
    writable: true
  - comment: Since DTDLv2 doesn't support arrays for Properties, a single string will
      be used.
    description: List of comma separated URLs to one or more related entities.
    displayName: See also
    name: refSeeAlso
    schema:
      primitiveType: string
    writable: true
  - description: Tourist area at which this museum is located. Precise semantics might
      depend on the application or target country or region. For instance Costa del
      Sol.
    displayName: Tourist area
    name: touristArea
    schema:
      primitiveType: string
    writable: true
status: {}
---
# apiVersion: dtd.ktwin/v0
# kind: TwinInstance
# metadata:
#   name: ngsi-ld-city-museum-001
#   namespace: ktwin
# spec:
#   interface: ngsi-ld-city-museum
#   template:
#     metadata:
#     spec:
#       containers:
#       - image: dev.local/ktwin/edge-service:0.1
#         imagePullPolicy: IfNotPresent
#         name: ngsi-ld-city-museum-001
#         resources: {}
# status: {}
