apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:
  name: ngsi-ld-city-pointofinterest
  namespace: ktwin
spec:
  comment: 'Original source: https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/PointOfInterest/doc/spec.md'
  description: 'Global description: This entity contains a harmonised geographic description
    of a Point of Interest'
  displayName: Point of Interest
  extendsInterface: ngsi-ld-city-ngsildbasemodel
  id: ngsi-ld-city-pointofinterest
  properties:
  - comment: Required property. Since DTDLv2 doesn't support arrays for Properties,
      a single string will be used.
    description: 'Category of this point of interest. Allowed values: Those defined
      by the Factual taxonomy together with the extended categories described by the
      specification. For instance the value 113 corresponds to beaches, and the value
      311 corresponds to museums.'
    displayName: Category
    name: category
    schema:
      primitiveType: string
    writable: true
  - description: The geographic area where a service or offered item is provided
    displayName: Area served
    name: areaServed
    schema:
      primitiveType: string
    writable: true
  - comment: Since DTDLv2 doesn't support arrays for Properties, a single string will
      be used.
    description: List of comma separated URLs to one or more related entities.
    displayName: See also
    name: refSeeAlso
    schema:
      primitiveType: string
    writable: true
status: {}
---
# apiVersion: dtd.ktwin/v0
# kind: TwinInstance
# metadata:
#   name: ngsi-ld-city-pointofinterest-001
#   namespace: ktwin
# spec:
#   interface: ngsi-ld-city-pointofinterest
#   template:
#     metadata:
#     spec:
#       containers:
#       - image: dev.local/ktwin/edge-service:0.1
#         imagePullPolicy: IfNotPresent
#         name: ngsi-ld-city-pointofinterest-001
#         resources: {}
# status: {}
