apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:
  name: ngsi-ld-city-beach
  namespace: ktwin
spec:
  comment: 'Original source: https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/Beach/doc/spec.md'
  description: 'Global description: This entity contains a harmonised geographic description
    of a beach.'
  displayName: Beach
  extendsInterface: ngsi-ld-city-ngsildbasemodel
  id: ngsi-ld-city-beach
  properties:
  - comment: Since DTDLv2 doesn't support arrays for Properties, a single string will
      be used.
    description: Type of beach according to different criteria. Enum:'whiteSand, urban,
      isolated, calmWaters, blueFlag, Q-Quality, strongWaves, windy, blackSand'. Or
      any other value needed by an application.
    displayName: Beach type
    name: beachType
    schema:
      primitiveType: string
    writable: true
  - description: Typical occupation rate of this beach. Enum:'low, medium, high'
    displayName: Occupation rate
    name: occupationRate
    schema:
      enumType:
        enumValues:
        - displayName: Low
          enumValue: low
          name: low
        - displayName: Medium
          enumValue: medium
          name: medium
        - displayName: High
          enumValue: high
          name: high
        valueSchema: string
    writable: true
  - comment: Since DTDLv2 doesn't support arrays for Properties, a single string will
      be used.
    description: Describes different facilities offered by this beach. Enum:'promenade,
      showers, cleaningServices, lifeGuard, sunshadeRental, sunLoungerRental, waterCraftRental,
      toilets, touristOffice, litterBins, telephone,surfPracticeArea, accessforDisabled'
    displayName: Facilities
    name: facilities
    schema:
      primitiveType: string
    writable: true
  - comment: Since DTDLv2 doesn't support arrays for Properties, a single string will
      be used.
    description: Enum:'privateVehicle, boat, onFoot, publicTransport'. Describes how
      to get to this beach.
    displayName: Access type
    name: accessType
    schema:
      primitiveType: string
    writable: true
  - description: The geographic area where a service or offered item is provided
    displayName: Area served
    name: areaServed
    schema:
      primitiveType: string
    writable: true
  - description: Length of this beach
    displayName: Length
    name: length
    schema:
      primitiveType: double
    writable: true
  - description: Width of this beach
    displayName: Width
    name: width
    schema:
      primitiveType: double
    writable: true
  - comment: Since DTDLv2 doesn't support arrays for Properties, a single string will
      be used.
    description: List of comma separated URLs to one or more related entities.
    displayName: See also
    name: refSeeAlso
    schema:
      primitiveType: string
    writable: true
status: {}
---
# apiVersion: dtd.ktwin/v0
# kind: TwinInstance
# metadata:
#   name: ngsi-ld-city-beach-001
#   namespace: ktwin
# spec:
#   interface: ngsi-ld-city-beach
#   template:
#     metadata:
#     spec:
#       containers:
#       - image: dev.local/ktwin/edge-service:0.1
#         imagePullPolicy: IfNotPresent
#         name: ngsi-ld-city-beach-001
#         resources: {}
# status: {}
