apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:
  name: ngsi-ld-city-store
  namespace: ktwin
spec:
  comment: 'Original source: https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/Store/doc/spec.md'
  description: 'Global description: This entity Type models stores/shops in the city.'
  displayName: Store
  extendsInterface: ngsi-ld-city-ngsildbasemodel
  id: ngsi-ld-city-store
  properties:
  - description: The geographic area where a service or offered item is provided
    displayName: Area served
    name: areaServed
    schema:
      primitiveType: string
    writable: true
  - comment: Since DTDLv2 doesn't support arrays for Properties, a single string will
      be used.
    description: Category of the store. Enum:'AutoPartsStore,BikeStore,BookStore,ClothingStore,ComputerStore,ConvenienceStore,DepartmentStore,ElectronicsStore,Florist,FurnitureStore,GardenStore,GroceryStore,HardwareStore,HobbyShop,HomeGoodsStore,JewelryStore,LiquorStore,MensClothingStore,MobilePhoneStore,MovieRentalStore,MusicStore,OfficeEquipmentStore,OutletStore,PawnShop,PetStore,ShoeStore,SportingGoodsStore,TireShop,ToyStore,WholesaleStore'
    displayName: Category
    name: category
    schema:
      primitiveType: string
    writable: true
  - comment: Since DTDLv2 doesn't support arrays for Properties, a single string will
      be used.
    description: Currencies accepted in this store. It uses ISO 4217 currency format
      (e.g. USD, EUR)
    displayName: Currencies accepted
    name: currenciesAccepted
    schema:
      primitiveType: string
    writable: true
  - description: The email address of this store.
    displayName: Email
    name: email
    schema:
      primitiveType: string
    writable: true
  - comment: URL to the logo
    description: An associated logo for this store.
    displayName: Logo
    name: logo
    schema:
      primitiveType: string
    writable: true
  - comment: Since DTDLv2 doesn't support arrays for Properties, a single string will
      be used.
    description: Payment method accepted in this store.
    displayName: Payment accepted
    name: paymentAccepted
    schema:
      primitiveType: string
    writable: true
  - description: The telephone number of this store.
    displayName: Telephone
    name: telephone
    schema:
      primitiveType: string
    writable: true
  - description: Website with information about the store.
    displayName: Website URL
    name: url
    schema:
      primitiveType: string
    writable: true
status: {}
---
# apiVersion: dtd.ktwin/v0
# kind: TwinInstance
# metadata:
#   name: ngsi-ld-city-store-001
#   namespace: ktwin
# spec:
#   interface: ngsi-ld-city-store
#   template:
#     metadata:
#     spec:
#       containers:
#       - image: dev.local/ktwin/edge-service:0.1
#         imagePullPolicy: IfNotPresent
#         name: ngsi-ld-city-store-001
#         resources: {}
# status: {}
